version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: tienda-frontend-u18
    ports:
      - "8118:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: tienda-backend-u18
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    ports:
      - "3018:3001"
    depends_on:
      - db

  db:
    build: ./db
    command: --innodb-use-native-aio=0
    container_name: tienda-db-u18
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
