name: Deploy Tienda Bastian

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          # El punto (.) significa "construye lo que encuentres aquí"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tienda-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tienda-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update Container
        uses: appleboy/ssh-action@master
        with:
          host: elservidor.redirectme.net
          username: user5
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tienda-backend:latest
            docker stop tienda-backend-u05 || true
            docker rm tienda-backend-u05 || true
            docker run -d --name tienda-backend-u05 -p 3005:3001 ${{ secrets.DOCKER_USERNAME }}/tienda-backend:latest
